version: '3'

## Networking
###############################################################################
networks:
  default:
    external:
      name: nginx-proxy

# Volumes
##############################################################################
volumes:
    krono-organizer: ~

## Services
###############################################################################
services:
    nginxproxy:
      image: jwilder/nginx-proxy
      container_name: nginxproxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
    php:
       build:
           context: ./docker/php
           dockerfile: Dockerfile
           args:
               useruid: ${UID}
               username: app
       logging:
           driver: "json-file"
           options:
               max-size: "10000k"
       environment:
           DEBUG: 1
           ENABLE_SSH: 1
       working_dir: "/var/www/app/"
       user: app
       hostname: "krono-organizer"
       volumes:
           # Директория с проектом
           - "./:/var/www/app/"
           # Кеш и всё всё всё для композитора
           - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
           # Конфигурация php
           - "./docker/php/php.ini:/usr/local/etc/php/php.ini:ro"
           - "./docker/php/fpm_pool.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro"
           - "./docker/php/logs/:/var/logs/"
           # Директория для временной папки
           - "./docker/php/tmp:/tmp"
           # Конфигурация для гит
           - "${HOME}/.gitconfig:/home/app/.gitconfig:ro"
           # Секретные ключи ssh
           - "${SSH_KEY_PATH}:/home/app/.ssh"
           - "./docker/php/tmp.sh:/home/app/run.sh"
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
               username: app
               useruid: ${UID}
        ports:
           - "8001:80"
           # Для статуса сервера
           - "8003:8082"
        volumes:
           - ".:/var/www/app"
           - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
           - "./docker/nginx/logs:/var/log/nginx"
        links:
           - php
        environment:
          VIRTUAL_HOST: api.krono-organizer.ru

    db:
        image: mysql:5.7
        volumes:
            - krono-organizer:/var/lib/mysql
        ports:
          - "${EXTERNAL_MYSQL_PORT}:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'


