version: '3'

# Volumes
volumes:
    krono-organizer: ~

## Services
services:
    php:
       build:
           context: ./docker/php
           dockerfile: Dockerfile
           args:
               useruid: ${UID}
               username: app
       logging:
           driver: "json-file"
           options:
               max-size: "10000k"
       environment:
           DEBUG: 1
           ENABLE_SSH: 1
       working_dir: "/var/www/app/"
       user: app
       volumes:
           # Директория с проектом
           - "./:/var/www/app/"
           # Кеш и всё всё всё для композитора
           - "/home/${USERNAME}/.composer/cache:/home/app/.composer/cache"
           # Конфигурация php
           - "./docker/php/php.ini:/usr/local/etc/php/php.ini:ro"
           - "./docker/php/fpm_pool.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro"
           - "./docker/php/logs/:/var/logs/"
           # Директория для временной папки
           - "./docker/php/tmp:/tmp"
           # Конфигурация для гит
           - "${HOME}/.gitconfig:/home/app/.gitconfig:ro"
           # Секретные ключи ssh
           - "/home/${USERNAME}/.ssh:/home/app/.ssh"
           - "./docker/php/tmp.sh:/home/app/run.sh"
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
               username: app
               useruid: ${UID}
        ports:
           - "80:80"
        volumes:
           - ".:/var/www/app"
           - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
           - "./docker/nginx/logs:/var/log/nginx"
        links:
           - php
#        environment:
#          VIRTUAL_HOST: api.krono-organizer.ru

    db:
      image: postgres:12.2
      environment:
        POSTGRES_PASSWORD: krono-organizer
        POSTGRES_USER: krono-organizer
        POSTGRES_DB: "krono-organizer"
      volumes:
        - "./docker/postgres/data:/var/lib/postgresql/data"
        - "/home/${USERNAME}/:/var/data"
      ports:
        - "${EXTERNAL_PGSQL_PORT}:5432"
      restart: always

